variable "box_basename" {}
variable "build_directory" {}
variable "build_timestamp" {}
variable "cpus" {}
variable "disk_size" {}
variable "guest_additions_url" {}
variable "headless" {}
variable "http_directory" {}
variable "iso_checksum" {}
variable "iso_name" {}
variable "ks_path" {}
variable "memory" {}
variable "mirror_directory" {}
variable "mirror" {}
variable "name" {}
variable "preseed_path" {}
variable "template" {}
variable "version" {}
